# Generated by Django 4.1.7 on 2023-02-24 17:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_company_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='balancesheet',
            field=models.FileField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage('/balancesheet')),
        ),
        migrations.AddField(
            model_name='company',
            name='cash_flow',
            field=models.FileField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage('/cash_flow')),
        ),
        migrations.AddField(
            model_name='company',
            name='income_statement',
            field=models.FileField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage('/income_statement')),
        ),
    ]
