# Generated by Django 4.1.7 on 2023-02-25 10:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0003_company_balancesheet_company_cash_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='history',
            field=models.FileField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage('/history')),
        ),
    ]
