# Generated by Django 4.1.7 on 2023-08-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0006_stockinportfolio_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinportfolio',
            name='sold_commission',
        ),
        migrations.RemoveField(
            model_name='stockinportfolio',
            name='sold_date',
        ),
        migrations.RemoveField(
            model_name='stockinportfolio',
            name='sold_price',
        ),
        migrations.RemoveField(
            model_name='stockinportfolio',
            name='sold_quantity',
        ),
    ]
