# Generated by Django 4.1.7 on 2023-08-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0007_remove_stockinportfolio_sold_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinportfolio',
            name='related_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='screener.portfolio'),
        ),
    ]
