# Generated by Django 4.1.7 on 2023-08-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0008_stockinportfolio_related_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinportfolio',
            name='purchase_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockinportfolio',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
