# Generated by Django 4.1.7 on 2023-08-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0009_alter_stockinportfolio_purchase_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='stocks',
            field=models.ManyToManyField(blank=True, to='screener.stockinportfolio'),
        ),
    ]
