# Generated by Django 4.1.7 on 2023-08-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0011_portfolio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
    ]
