# Generated by Django 4.1.7 on 2023-08-31 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0012_remove_portfolio_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='stocks',
            new_name='related_stocks',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stockinportfolio',
            name='related_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='screener.portfolio'),
        ),
    ]
